# meta file for fail2ban
---
galaxy_info:
  author: Nicolas Bigot
  description: Set up fail2ban in Ubuntu, RHEL-like, CentOS systems
  license: MIT
  min_ansible_version: 2.2.0
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - yakkety
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - system
    - networking
dependencies: []
